baseURL = "http://mtinone.com"
languageCode = "en-us"
title = "Marina Tinone"
copyright = "Marina Tinone"
theme = "cactus"
pluralizeListTitles = "false"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  description = "This website is home to the things I've written. I hope you enjoy reading them!"
  mainSection = "portfolio"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  showProjectsList = false
  rss = true

[[params.social]]
  name = "facebook"
  link = "https://facebook.com/mtinone"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/mtinone"

[[params.social]]
  name = "instagram"
  link = "https://instagram.com/mtinone"
